services:
  mysql:
    image: mysql:8.4
    container_name: leaveflow-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: leave_management
      MYSQL_USER: leave_user
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - leaveflow_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  backend:
    build:
      context: ./backend

    container_name: leaveflow-backend
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/leave_management
      SPRING_DATASOURCE_USERNAME: leave_user
      DB_PASSWORD: ${DB_PASSWORD}

      SERVER_PORT: 8082
      JWT_SECRET: ${JWT_SECRET}

      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      APP_EMPLOYEE_PASSWORD: ${APP_EMPLOYEE_PASSWORD}

    ports:
      - "8082:8082"


  frontend:
    build:
      context: ./frontend

    container_name: leaveflow-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:80"

volumes:
  leaveflow_mysql_data:
